# Generated by Django 3.0.5 on 2020-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
