# Generated by Django 3.0.5 on 2020-11-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre_usuario',
            new_name='usuario',
        ),
    ]
