# Generated by Django 3.1.2 on 2020-10-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Project',
        ),
    ]
