# Generated by Django 3.1.2 on 2020-10-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20201015_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
